

 #nombre local del archivo de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicios_examenes

#usuario root 123456
spring.datasource.username=postgres

#
spring.datasource.password=123456


#genera las tablas que tiene en los Script de manera automatica
# hibernate no permite valores booleanos ademas true siempre va a crear y borrar dat
spring.jpa.hibernate.ddl-auto=update

#permite imprimir todas las http Request en consola web
logging.level.org.hibernate.SQL=debug