spring.application.name=microservicios-examenes

#Asigna el puerto de cada instancia de manera aleatoria
server.port=${PORT :0}

#asigna el id de cada instancia de manera aleatoria
eureka.instance.instance-id=${pring.aplication.name}:${random.value}

#Le indica en que puerto se despliega eureka para conectarse

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=
spring.datasource.name=
spring.datasource.password=




